version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vina_2026_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: vinadb
    ports:
      - '5433:5432'
    volumes:
      - vina_db_data:/var/lib/postgresql/data

volumes:
  vina_db_data:
